### ISSUE TITLE
[BUG] Impossible to use with api-key (chatgpt)

### ISSUE THREAD

**Issue by tarakanovalexey** [explyt/explyt-test-issues#2]
### Problem details

Chatgpt is available from plugin, but fails with error message:
Cannot reach OpenAI provider endpoint https://api.openai.com/v1/chat/completions. Change language model or provider in Settings, please.
It seems that completions is not available or application get wrong api-key, not the one I am currently using.

### Steps to reproduce

1) Register new api-key from personal chatgpt account (https://platform.openai.com/settings/profile?tab=api-keys)
2) Fill in plugin settings in intellij idea
3) Try to generate tests for your any method in your project

### Additional information

![изображение](https://github.com/user-attachments/assets/63998fc1-7c84-48d9-a4d1-b6a94654e45c)

### Plugin version

1.2 (from zip that was provided in telegram group)

### Build system

Gradle

### LLM provider

Open AI

### LLM model

GPT-4o mini

### Test framework

Not important

### Mock framework

Not important

**Comment by tarakanovalexey** [comment]
1. Yes, I do:
![изображение](https://github.com/user-attachments/assets/15035e15-ad5f-4a78-a8e1-39d24d77f95a)
2. My api key has all permissions:
![изображение](https://github.com/user-attachments/assets/2b5ad38d-e5ac-42ba-9b3b-1a3d9902d63e)
3. I already checked it and I reroute all packages for openai into vpn, here is curl execution:
![изображение](https://github.com/user-attachments/assets/76c5f585-9ee3-4317-9598-d92a3a444c10)
![изображение](https://github.com/user-attachments/assets/74a0d22f-a139-4b0d-b9df-7ad67d15feb6)

**Comment by Columpio** [comment]
Still, I cannot reproduce this.

I obtained the same plugin .zip, loaded it, set the same `Explyt Tests` settings and tried running plugin with both enabled and disabled VPN, and with both legacy and new project API keys. Everything works just fine.

**Comment by tarakanovalexey** [comment]
The problem was that I had 1.2 plugin version. I got 1.3 and it works fine.

**Comment by tarakanovalexey** [comment]
done
